create table mole.clinics (
  clinic_id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY
  , clinic_date DATE
  , clinic_location_id INTEGER

  , created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_by INTEGER NOT NULL
  , modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  , modified_by INTEGER NOT NULL
  , deleted BOOLEAN DEFAULT FALSE NOT NULL
)
;
